- hosts: webservers
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    notify:
      reload service httpd
  - name: start and enable httpd
    systemd:
      name: httpd
      state: started
      enabled: yes
  - name: permit traffic in default zone for https service
    firewalld:
      port: "{{ http_port }}"
      permanent: yes
      state: enabled
  - name: copy index.html file to the managed host
    copy:
      src: "{{ html_page_src }}"
      dest: "{{ html_page_dest }}"
  handlers:
  - name: reload service httpd
    systemd:
      name: httpd
      state: restarted
