---
- name: Build Docker Image
  hosts: all
  become: true
  tasks:
    - name: Update yum cache
      yum:
        name: '*'
        state: latest


    - name: Install Docker dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/centos/gpg | sudo gpg --import -

    - name: Add Docker YUM repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install python3-pip package
      yum:
        name: python3-pip
        state: present  

    - name: Install Docker Python package
      pip:
        name: docker
        state: present

    - name: Copy Dockerfile to the target machine
      copy:
        src: Dockerfile
        dest: /tmp/Dockerfile
    - name: Copy public-html directory to the target machine
      copy:
        src: ./public-html
        dest: /tmp/public-html
    - name: Build Docker image
      command: docker build -t http /tmp
    - name: restart_docker
      service:
        name: docker
        state: restarted    

